ChatPlayGround/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# auth views 
from django.contrib.auth import views as auth_views

from personal.views import (
    home_screen_view
)

from accounts.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view
)


urlpatterns = [
    path('', home_screen_view, name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace = 'friend')),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('register/', register_view, name = 'register'),
    path('search/', account_search_view, name = 'search'),

    # Password reset links 
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)








  

accounts/urls.py
from django.urls import path
from .views import (
    account_view,
    edit_account_view,
    crop_image
)

app_name = "accounts"

urlpatterns = [
    path('<user_id>/', account_view, name='view'),
    path('<user_id>/edit/', edit_account_view, name='edit'),
    path('<user_id>/edit/cropImage/', crop_image, name='crop_image'),
]

friend/urls.py
from django.urls import path

from .views import (
	send_Friend_request,
)

app_name = "friend"

urlpatterns = [
	path("friend_request/", send_Friend_request, name ="friend-request"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# create a new user 
class MyAccountManager(BaseUserManager):

    def create_user(self, email, username, password = None):
        if not email:
            raise ValueError("User must have an email address.")
        if not username:
            raise ValueError("User must have a username.")
        user = self.model(
            email = self.normalize_email(email),
            username = username
        )

        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using = self._db)
        return user

# for uploading image
def get_profile_image_filepath(self, filename):
    return f'profile_images/{self.pk}/{"profile_image.png"}'

# getting image 
def get_default_profile_image():
    return 'default.png'


# overriding the abstract base user 
class Account(AbstractBaseUser):

    email           = models.EmailField(verbose_name = 'email', max_length=60, unique=True )
    username        = models.CharField(max_length=30, unique=True)
    date_joined     = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name="last login", auto_now = True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    profile_image   = models.ImageField(max_length = 255, upload_to = get_profile_image_filepath, null = True, blank = True, default = get_default_profile_image)
    hide_email      = models.BooleanField(default=True)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'         #django uses username for login but i change this with email for login
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/{self.pk}/'):]

    def has_perm(self, perm, obj = None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text="Required. Add a valid email address.")

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2')


        def clean_email(self):
            email = self.cleaned_data['email'].lower()
            try:
               account = Account.objects.get(email = email)
            except Exception as e:
                return email
            raise forms.ValidationError(f" Email {email} is already there")
        
        def clean_username(self):
            username = self.cleaned_data['username'].lower()
            try:
               account = Account.objects.get(username = username)
            except Exception as e:
                return username
            raise forms.ValidationError(f" Username { username } is already there")

class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label = "Password", widget = forms.PasswordInput)

    class Meta:
        model = Account
        fields = ("email", "password")

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email = email, password = password):
                raise forms.ValidationError("Invalid Login Credentials !")


# update user profile 

class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_email')
  
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email = email)
        except Exception as e:
            return email
        raise forms.ValidationError(f" Email {email} is already there")
            
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        try:
            account = Account.objects.get(username = username)
        except Exception as e:
            return username
        raise forms.ValidationError(f" Username { username } is already there")

    def save(self, commit = True):
        account = super(AccountUpdateForm, self).save(commit = False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email']
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']

        if commit:
            account.save()
        return account

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
# FORMS
from accounts.forms import AccountAuthenticationForm, RegistrationForm, AccountUpdateForm
# IMPORTED FOR CREATING LOGIN, LOGOUT AND AUTHENTICATING TO THE USER
from django.contrib.auth import login, authenticate, logout, views
# imported for BASE_URL
from django.conf import settings
# ACCOUNTS MODELS
from accounts.models import Account

# required for image cropping and saving

from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
import os
import cv2
import json
import base64
# import requests
from django.core import files

TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"

# import utils 
from friend.utils import get_friend_request_or_false
from friend.friend_request_status import FriendRequestStatus
from friend.models import FriendList, FriendRequest
# views

def register_view(request, *args, **kwargs):
    template_name = 'accounts/register.html'
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f"You are already authenticated as {user.email}.")

    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # after registerration user will automatic login
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            destination = get_redirect_if_exists(request)
            if destination:
                return redirect(destination)
            return redirect("home")

        else:
            context['registration_form'] = form

    return render(request, template_name, context)


def logout_view(request):
    logout(request)
    return redirect('home')


def login_view(request, *args, **kwargs):
    template_name = 'accounts/login.html'
    context = {}

    if request.user.is_authenticated:
        return redirect('home')

    destination = get_redirect_if_exists(request)
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
                return redirect('home')
        else:
            context['login_form'] = form

    return render(request, template_name, context)


def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.Get.get("next"):
            redirect = str(request.GET.get('next'))


def account_view(request, *args, **kwargs):
    """
        -Logic here is kidn of tricky
        is_self (boolean)
            -1: NO_REQUEST_SENT
            0:THEM_SENT_TO_YOU
            1:YOU_SENT_TO_THEM
    """
    context = {}
    template_name = 'accounts/account.html'
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except Account.DoesNotExist:
        return HttpResponse("that user doesn't exist.")

    # if account exists
    if account:
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.email
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email
        try:
            friend_list = FriendList.objects.get(user = account)
        except FriendList.DoesNotExist:
                friend_list = FriendList(user = account)
                friend_list.save()
        friends = friend_list.friends.all()
        context['friends'] = friends


        # state tamplate  variables
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        friend_requests = None

        user = request.user
        if user.is_authenticated and user != account:
            is_self = False
            if friends.filter(id = user.id):
                is_friend = True
            else:
                is_friend = False
                # CASE1: Request has been sent from them to you
                if get_friend_request_or_false(sender = account, receiver = user) != False:
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context["pending_friend_request_id"] = get_friend_request_or_false(sender = account, receiver = user).id
                #CASE 2:Request has been sent to them from you:
                # FriendRequestStatus.YOU_SENT_TO_THEM
                elif get_friend_request_or_false(sender = account, receiver = user) != False:
                    request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value    

                else:
                    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value   
        elif not user.is_authenticated:
            is_self = False

        # user looking to the self profile 
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver = user, is_active = True) 
            except:
                pass


        context["is_self"] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
        context["request_sent"] = request_sent
        context["friend_requests"] = friend_requests

        return render(request, template_name, context)


# search functionality
def account_search_view(request, *args, **kwargs):
    context = {}
    if request.method == "GET":
        search_query = request.GET.get("q")
        if len(search_query) > 0:
            search_results = Account.objects.filter(email__icontains=search_query).filter(
                username__icontains=search_query).distinct()
            user = request.user
            accounts = []  # [(account1, True), (account2, False), ...]
            for account in search_results:
                accounts.append((account, False))  # you have no friends yet
            context['accounts'] = accounts

    return render(request, "accounts/search_result.html", context)


# views commentd
"""
context = {}
	if request.method == "GET":
		search_query = request.GET.get("q")
		if len(search_query) > 0:
			search_results = Account.objects.filter(email__icontains=search_query).filter(
			    username__icontains=search_query).distinct()
			user = request.user
			accounts = [] # [(account1, True), (account2, False), ...]
			for account in search_results:
				accounts.append((account, False)) # you have no friends yet
			context['accounts'] = accounts

	return render(request, "accounts/search_results.html", context)
"""
# end views


def edit_account_view(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("login")
    user_id = kwargs.get("user_id")
    account = Account.objects.get(pk=user_id)
    if account.pk != request.user.pk:
        return HttpResponse("You cannot edit someone elses profile.")
    context = {}
    if request.POST:
        form = AccountUpdateForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            # delete old profile image so the name preserved
            # account.profile_image.delete()
            form.save()
            # new_username = form.cleaned_data['username']
            return redirect("accounts:view", user_id=account.pk)
        else:
            form = AccountUpdateForm(request.POST, instance=request.user,
                                     initial={
                                         "id": account.pk,
                                         "email": account.email,
                                         "username": account.username,
                                         "profile_image": account.profile_image,
                                         "hide_email": account.hide_email,
                                     }
                                     )
            context['form'] = form
    else:
        form = AccountUpdateForm(
            initial={
                "id": account.pk,
                "email": account.email,
                "username": account.username,
                "profile_image": account.profile_image,
                "hide_email": account.hide_email,
            }
        )
        context['form'] = form
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, "accounts/edit_account.html", context)


def save_temp_profile_image_from_base64String(imageString, user):
    INCORRECT_PADDING_EXCEPTION = "Incorrect padding"
    try:
        if not os.path.exists(settings.TEMP):
            os.mkdir(settings.TEMP)
        if not os.path.exists(settings.TEMP + "/" + str(user.pk)):
            os.mkdir(settings.TEMP + "/" + str(user.pk))
        url = os.path.join(settings.TEMP + "/" + str(user.pk),
                           TEMP_PROFILE_IMAGE_NAME)
        storage = FileSystemStorage(location=url)
        image = base64.b64decode(imageString)
        with storage.open('', 'wb+') as destination:
            destination.write(image)
            destination.close()
        return url
    except Exception as e:
        # print("exception: " + str(e))
        # workaround for an issue I found
        if str(e) == INCORRECT_PADDING_EXCEPTION:
            imageString += "=" * ((4 - len(imageString) % 4) % 4)
            return save_temp_profile_image_from_base64String(imageString, user)
    return None


def crop_image(request, *args, **kwargs):
    payload = {}
    user = request.user
    if request.POST and user.is_authenticated:
        try:

accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'friend/snippets/send_friend_request.html' %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
	.message-btn-text{
		font-weight: 500;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="Profile Pic" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		{% if is_self %}
		  		<a  class="mt-4 btn btn-primary" href="{% url 'accounts:edit' user_id=id %}">Update</a> <!--id is coming from account_view() in views.py context is set there-->
				<div class="d-flex flex-column mt-4">
					<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
				</div>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<button id="id_cancel_{{id}}" class=" btn btn-sm btn-danger" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>Decline</button>
  					<button id="id_confirm_{{id}}" class="btn btn-sm btn-success ml-2" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>Accept</button>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == -1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}
					
					
				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
					</div>
				{% endif %}
				
				<!-- TODO -->
				<!-- Friend list link -->
		  		<div class="d-flex flex-column pt-4">
					<a href="#">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							 <span class="friend-text"><i class="far fa-handshake  fa-2x text-primary"></i>  Friends ({{ friends|length }})</span>
						</div>
					</a>
				</div>

			</div>

			<!-- TODO -->
			{% if friend_requests %}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
					<a href="#">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="friend-text"><i class="fas fa-people-carry fa-2x text-primary"></i> Friend Requests ({{ friend_requests|length}})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}

			{% if is_friend %}
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4" onclick="createOrReturnPrivateChat('{{id}}')">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			{% endif %}

		</div>
		{% endif %}

		
	</div>
</div>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js">

	// called from base_js.html
	//preloadImage("{{profile_image|safe}}", 'id_profile_image')

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}


	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			//cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			//removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		//acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		//declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}

	function sendFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax()({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:friend-request' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request sent."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	
</script>

{#% include 'snippets/accept_friend_request.html' %#}
{#% include 'snippets/decline_friend_request.html' %#}
{#% include 'snippets/cancel_friend_request.html' %#}
{#% include 'snippets/remove_friend.html' %#}
{#% include 'chat/create_or_return_private_chat.html' %#}



{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin">
		  <div class="card-body">
		    <form class="form-signin" method="post">{% csrf_token %}
				<div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" src="{% static 'default.png' %}" alt="shivam shankhdhar" width="100" height="100">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
<br>
				{% for field in login_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if login_form.non_field_errors %}
				<div style="color: red">
				<p>{{login_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
				</form>

				<div class="d-flex flex-column my-4">
					<a class="m-auto" href="{% url 'password_reset' %}">Reset password</a>
				</div>
		  </div>
		</div>
		
	</div>
</div>

{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
 {% load static %}

{% block content %}

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin">
		  <div class="card-body">
		    <form class="form-signin" method="post">{% csrf_token %}
				<div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" src="{% static 'default.png' %}" alt="avatar" width="100" height="100">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>

				<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

				<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>
<br>
				{% for field in registration_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if registration_form.non_field_errors %}
				<div style="color: red">
					<p>{{registration_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

				</form>
		  </div>
		</div>
		
	</div>
</div>

{% endblock content %}

accounts/templates/accounts/search_result.html
<!-- This is basically exactly the same as friend_list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">

		{% if accounts %}
		<div class="d-flex flex-row flex-wrap">
		{% for account in accounts %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'accounts:view' user_id=account.0.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'accounts:view' user_id=account.0.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{account.0.username}}</h4>
					{% if account.1 %}
					<p class="card-text"><a href="#" onclick="createOrReturnPrivateChat('{{account.0.id}}')">Send a Message</a></p>
					{% endif %}
					
				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if account.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends 
						</p>
						<i class="far fa-check-circle text-success"></i>
					</div>
				{% else %}
					{% if account.0 !=  request.user %}
						<div class="">
							<button class="btn btn-sm btn-danger disable" style="cursor: no-drop;">
								Not Friends 
							</button>
							<!-- <i class="far fa-times-circle text-danger"></i> -->
						</div>
					{% endif %}
				{% endif %}
				{% if account.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<i class="far fa-user-circle text-primary"></i>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>


{#%  include 'chat/create_or_return_private_chat.html' %#}

<script type="text/javascript">
	function createOrReturnPrivateChat(user_id){
		// Just a placeholder
	}
</script>

{% endblock content %}