ChatPlayGround/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# auth views 
from django.contrib.auth import views as auth_views

from personal.views import (
    home_screen_view
)

from accounts.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view
)


urlpatterns = [
    path('', home_screen_view, name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls', namespace = 'friend')),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('register/', register_view, name = 'register'),
    path('search/', account_search_view, name = 'search'),

    # Password reset links 
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)








  

accounts/urls.py
from django.urls import path
from .views import (
    account_view,
    edit_account_view,
    crop_image
)

app_name = "accounts"

urlpatterns = [
    path('<user_id>/', account_view, name='view'),
    path('<user_id>/edit/', edit_account_view, name='edit'),
    path('<user_id>/edit/cropImage/', crop_image, name='crop_image'),
]

friend/urls.py
from django.urls import path

from .views import (
	send_Friend_request,
)

app_name = "friend"

urlpatterns = [
	path("friend_request/", send_Friend_request, name ="friend-request"),
]

templates/snippets/base_css.html
<style type="text/css">
:root{
    --main-background-color:#f2f2f2;
    --dark-background-color:#a2a2a2;
    --secondary-text-color:#808080;
    --light-primary-text-color:#0080ff;
}
body{
        background-color: var(--main-background-color);  
        font-family: 'Segoe UI';
        font-weight: 380;
    }
.header{
        font-family: 'Segoe UI';
        font-weight: 380;
    }
.main{
        min-height: 100vh;
        height: 100%;
    }
.footer{
    font-family: 'Segoe UI';
    font-weight: 380;
    }
    

    /* register css */

    
  .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
 /* login css */
 
 .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

</style>

templates/snippets/base_js.html
<script type="text/javascript">
    // write some code 
</script>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">Shivam shankhdhar| 2020</p>
</div>
<!-- End Footer -->

templates/snippets/header.html
{% load static %}
<style>
    .font-size{
        font-size:20px;
        /* margin-top: 10px; */
    }
    </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Chat Play Ground </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav  col col-9">
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="#"> Feed <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Friends</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Friend Request</a>
            </li>
            {% endif  %}
            <!-- <li class="nav-item">
              <a class="nav-link " href="#" tabindex="-1" ></a>
            </li> -->
            <form class="d-flex lg-ml-3" onsubmit= "return executeQuery();">
                <input class="form-control " name="friend_search" type="search" placeholder="Search friends..." aria-label="Search" style="width: 20rem; outline: none;" id="id_q_small">
                <button class="btn btn-primary btn-sm" type="submit" style="margin-left: 10px;width: 100px;border:none">Search</button>
              </form>
          </ul>
          <ul class="navbar-nav ml-3 col-3 justify-content end row">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown" >
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   <img src="{{request.user.profile_image.url }}"  class="border rounded-circle" width ="30" height= "30"  alt="">
                </a>
                <div class="dropdown-menu dropstart" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:view' user_id=request.user.id %}"><i class="far fa-user-circle"></i> My Profile</a>
                    <!-- <a class="dropdown-item" href="#"><i class="fas fa-cog"></i> Notifications</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cog"></</a> -->
                    <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
              </li>
             
              <li class="nav-item">
                  <!-- notifications  -->
                <a href="#" class=" nav-link active">
                    <i class="far fa-bell font-size"></i>  <span class="badge badge-primary badge-pill">0</span>
                    
                </a>
            </li>
    
            <li class="nav-item">
                <!-- messages  -->
                <a href="#" class=" nav-link active">
                    <i class="far fa-comment font-size"></i>  <span class="badge badge-primary badge-pill">0</span>
                    
                </a>
            </li>
    
            <!-- <li class="nav-item">
                <a class="nav-link active" href="#" ><i class="far fa-bell"></i> Messages</a>
            </li> -->
            
              {% else %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'login' %}" > Login <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'register' %}" > Sign Up <i class="fas fa-user-plus"></i></a>
                </li>
              {% endif %}
          </ul>
        </div>
       
      </nav>

<script type="text/javascript">
    function executeQuery(){
        var query = document.getElementById("id_q_small").value
        window.location.replace("{% url 'search' %}?q=" + query)
        return false
    }
</script>